sudo: required
services:
  - docker

before_install:
  - docker build -t amourycodes/docker-react-frontend -f Dockerfile.dev .

script: 
  - docker run amourycodes/docker-react-frontend npm run test -- --coverage