sudo: required
services:
  - docker

before_install:
  - docker build -t amourycodes/docker-react-frontend -f Dockerfile.dev .

script: 
  - docker run amourycodes/docker-react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-simple-frontend"
  env: "DockerReactSimpleFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-073682385503"
  bucket_path: "docker-react-simple-frontend"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"